Repository 42-Piscine-Batch-4/discordbot, pull requests merged in 2024-05, with the labels that each got.

#23 build: add ecosystem file
  ecosystem.config.js
  package.json
Labels: enhancement

#30 Feat: Add echo command
  src/commands/echo.ts
  src/commands/index.ts
  src/index.ts
Labels: enhancement

#33 Feat: Add Dice command
  src/commands/dice.ts
  src/commands/index.ts
Labels: enhancement

#20 feat: add sort_desc slash command.
  package.json
  src/commands/index.ts
  src/commands/sort_desc.ts
Labels: enhancement

#35 Sort asc command
  src/commands/index.ts
  src/commands/sort_asc.ts
  src/commands/sort_desc.ts
Labels: enhancement

#36 Changed logic to match declarative programming style
  src/commands/sort_asc.ts
Labels: enhancement

#37 re-added missing shout command export
  src/commands/index.ts
Labels: bug

#39 Update README.md
  README.md
Labels: documentation

#40 feat: add /rps command.
  package-lock.json
  package.json
  src/commands/index.ts
  src/commands/rps.ts
Labels: enhancement

#41 feat: added calc command #2
  package-lock.json
  package.json
  src/commands/calc.ts
  src/commands/index.ts
Labels: enhancement

#68 fix: remove string prototype modification
  src/commands/rps.ts
Labels: bug

#69 Build/add-npm-i
  package.json
  src/commands/rev.ts
  src/commands/rps.ts
  src/commands/sort_desc.ts
Labels: bug

#90 feat: add /caesar command.
  src/commands/caesar.ts
  src/commands/index.ts
Labels: enhancement

#86 feat: added member_count command #21
  src/commands/index.ts
  src/commands/member_count.ts
Labels: enhancement

#93 Update again to last
  src/commands/last.ts
Labels: enhancement

#94 feat: added celsius command #62
  package-lock.json
  package.json
  src/commands/bedtime.ts
  src/commands/caesar.ts
  src/commands/celsius.ts
  src/commands/index.ts
  src/commands/member_count.ts
Labels: enhancement

#99 fix: celsius-command
  package.json
  src/commands/index.ts
  src/commands/temperature.ts
Labels: bug

#100 Update README.md
  README.md
Labels: enhancement

#107 feat: implement horoscope command
  src/commands/horoscope.ts
  src/config.ts
  src/utils/format-string.ts
Labels: enhancement

#104 added proper timestamps and altcaps option to "/last" command
  src/commands/last.ts
  src/config.ts
  src/utils/alt-capitalize-string.ts
  src/utils/dayjs.ts
Labels: enhancement

#105 Update: formating and return 2 other temp type
  src/commands/temperature.ts
Labels: enhancement

#109 Feat/currency
  package-lock.json
  package.json
  src/commands/currency.ts
  src/commands/index.ts
Labels: enhancement
